services:
  server:    
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DbConnectionString=${DB_CONNECTION_STRING}
  db:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: askme-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
      - ConnectionString=${DB_CONNECTION_STRING}
    ports:
      - "1433:1433"
