services:
  server:    
    build:
      context: ./server
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DbConnectionString=${DB_CONNECTION_STRING}
      - SENDGRID_API_KEY
      - DEEPSEEK_API_KEY
  db:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: askme-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
      - ConnectionString=${DB_CONNECTION_STRING}
    ports:
      - "1433:1433"
  client:  
    build:
      context: ./client/ask-me
    ports:
      - "5173:5173"
